"""Machine-readable stability contracts for commands and artifacts."""

from __future__ import annotations

from typing import Any

from . import VERSION
from .config import CONFIG_MIGRATION_CONTRACT
from .formatting import markdown_table
from .paths import AUDIT_REPORT, DIST_DIR, GENERATED_TFVARS, RC_EVIDENCE_DIR

CONTRACT_SCHEMA_VERSION = 1
COMMAND_CONTRACTS: list[dict[str, Any]] = [
    {
        "command": "devsecops",
        "status": "stable",
        "scope": "first-success",
        "stable_flags": [],
        "formats": ["human"],
        "notes": "Shows compact project status and the shared next action without prompting.",
    },
    {
        "command": "devsecops menu",
        "status": "stable",
        "scope": "interactive",
        "stable_flags": [],
        "formats": ["human"],
        "notes": "Opens six product sections while keeping technical tools in nested hubs.",
    },
    {
        "command": "devsecops status",
        "status": "stable",
        "scope": "first-success",
        "stable_flags": ["--deep", "--strict", "--format", "--watch", "--interval"],
        "formats": ["human", "compact", "json"],
        "json_kind": "status",
        "notes": "Combines one project score, status areas, blockers, and the single next action.",
    },
    {
        "command": "devsecops setup",
        "status": "stable",
        "scope": "first-success",
        "stable_flags": ["--preset", "--generate", "--yes"],
        "formats": ["human"],
        "notes": "Single guided onboarding entry point; creates config only after confirmation.",
    },
    {
        "command": "devsecops criteria",
        "status": "stable",
        "scope": "release",
        "stable_flags": ["--format", "--evidence-dir", "--strict"],
        "formats": ["human", "json"],
        "json_kind": "v1-criteria",
        "notes": "Checks Version 1.0 criteria and stable-release evidence blockers.",
    },
    {
        "command": "devsecops config show",
        "status": "stable",
        "scope": "configuration",
        "stable_flags": ["--format"],
        "formats": ["toml", "json"],
        "notes": "Prints local source config. JSON is normalized with defaults and migrations applied.",
    },
    {
        "command": "devsecops config new",
        "status": "alias",
        "scope": "configuration",
        "stable_flags": ["--preset", "--force", "--generate"],
        "alias_for": "devsecops setup",
        "formats": ["human"],
        "notes": "Lower-level compatibility entry point. Prefer setup for a first run.",
    },
    {
        "command": "devsecops config validate",
        "status": "stable",
        "scope": "configuration",
        "stable_flags": ["--strict", "--format"],
        "formats": ["human", "compact", "json"],
        "json_kind": "config",
        "notes": "Validates config before Terraform, GitHub, or AWS operations.",
    },
    {
        "command": "devsecops config diff",
        "status": "stable",
        "scope": "configuration",
        "stable_flags": ["--preset", "--exit-code"],
        "formats": ["unified-diff"],
        "notes": "Shows canonical config drift or preset comparison.",
    },
    {
        "command": "devsecops config reset",
        "status": "stable",
        "scope": "configuration",
        "stable_flags": ["--preset", "--generate"],
        "formats": ["human"],
        "notes": "Creates a snapshot before replacing local source config.",
    },
    {
        "command": "devsecops config set",
        "status": "stable",
        "scope": "configuration",
        "stable_flags": ["<key>", "<value>", "--generate"],
        "formats": ["human"],
        "notes": "Only documented keys from the config schema are accepted.",
    },
    {
        "command": "devsecops config schema",
        "status": "stable",
        "scope": "configuration",
        "stable_flags": ["--format"],
        "formats": ["json", "markdown"],
        "notes": "Prints config fields, migration policy, and rollback expectations.",
    },
    {
        "command": "devsecops dry-run",
        "status": "stable",
        "scope": "first-success",
        "stable_flags": ["--preset", "--image-uri", "--environment"],
        "formats": ["human"],
        "notes": "No credentials or file writes required.",
    },
    {
        "command": "devsecops image validate",
        "status": "stable",
        "scope": "first-success",
        "stable_flags": ["--image-uri", "--environment", "--format"],
        "formats": ["human", "compact", "json"],
        "json_kind": "image-validation",
        "notes": "Checks image shape, immutability, region, and repository naming.",
    },
    {
        "command": "devsecops health",
        "status": "stable",
        "scope": "operations",
        "stable_flags": ["--url", "--timeout", "--format"],
        "formats": ["human", "compact", "json"],
        "json_kind": "health",
        "notes": "Read-only deployed /health validation.",
    },
    {
        "command": "devsecops generate",
        "status": "stable",
        "scope": "rendering",
        "stable_flags": ["--dry-run"],
        "formats": ["human"],
        "notes": "Writes deterministic CLI-owned artifacts from local source config.",
    },
    {
        "command": "devsecops report",
        "status": "stable",
        "scope": "reports",
        "stable_flags": ["--deep", "--format", "--output", "--print"],
        "formats": ["markdown", "json"],
        "json_kind": "audit-evidence",
        "notes": "Writes CLI-owned readiness report or attachable audit evidence.",
    },
    {
        "command": "devsecops evidence collect",
        "status": "stable",
        "scope": "reports",
        "stable_flags": ["--rc", "--output"],
        "formats": ["generated-files", "human"],
        "json_kind": "release-candidate-evidence",
        "notes": "Collects local release-candidate evidence artifacts under dist/devsecops.",
    },
    {
        "command": "devsecops doctor local",
        "status": "stable",
        "scope": "diagnostics",
        "stable_flags": ["--deep", "--strict", "--format"],
        "formats": ["human", "compact", "json"],
        "json_kind": "doctor-local",
        "notes": "Local config, files, tools, and render state.",
    },
    {
        "command": "devsecops doctor github",
        "status": "stable",
        "scope": "github",
        "stable_flags": ["--strict", "--format"],
        "formats": ["human", "compact", "json"],
        "json_kind": "github",
        "notes": "GitHub CLI, repository variables, and secrets.",
    },
    {
        "command": "devsecops doctor aws",
        "status": "stable",
        "scope": "aws",
        "stable_flags": ["--environment", "--strict", "--format"],
        "formats": ["human", "compact", "json"],
        "json_kind": "aws",
        "notes": "AWS identity, backend, and deployed resources.",
    },
    {
        "command": "devsecops doctor branch",
        "status": "stable",
        "scope": "github",
        "stable_flags": ["--branch", "--strict", "--format"],
        "formats": ["human", "compact", "json"],
        "json_kind": "branch-protection",
        "notes": "Branch protection and required checks.",
    },
    {
        "command": "devsecops doctor actions",
        "status": "stable",
        "scope": "github",
        "stable_flags": ["--limit", "--strict", "--format"],
        "formats": ["human", "compact", "json"],
        "json_kind": "github-actions-status",
        "notes": "Recent runs, failed jobs, failed steps, and next actions.",
    },
    {
        "command": "devsecops doctor all",
        "status": "stable",
        "scope": "diagnostics",
        "stable_flags": ["--deep", "--branch", "--environment", "--strict", "--format"],
        "formats": ["human", "compact", "json"],
        "json_kind": "doctor-all",
        "notes": "Combined local, GitHub, branch, and AWS diagnostics.",
    },
    {
        "command": "devsecops aws outputs",
        "status": "stable",
        "scope": "aws",
        "stable_flags": ["--environment", "--strict", "--format"],
        "formats": ["human", "json"],
        "json_kind": "aws-outputs",
        "notes": "Read-only deployed Lambda, API Gateway, and CloudWatch output inspection.",
    },
    {
        "command": "devsecops aws doctor",
        "status": "stable",
        "scope": "aws",
        "stable_flags": ["--environment", "--strict", "--format"],
        "formats": ["human", "compact", "json"],
        "json_kind": "aws",
        "notes": "Grouped alias for `devsecops doctor aws`; stable for scripts.",
    },
    {
        "command": "devsecops github setup",
        "status": "stable",
        "scope": "github",
        "stable_flags": ["--write", "--apply", "--deploy-role-arn", "--plan-role-arn", "--snyk-token"],
        "formats": ["shell", "human"],
        "notes": "Prints, writes, or applies repository variables/secrets through `gh`.",
    },
    {
        "command": "devsecops github status",
        "status": "stable",
        "scope": "github",
        "stable_flags": ["--limit", "--strict", "--format"],
        "formats": ["human", "compact", "json"],
        "json_kind": "github-actions-status",
        "notes": "Same output contract as `devsecops doctor actions`.",
    },
    {
        "command": "devsecops github branch",
        "status": "stable",
        "scope": "github",
        "stable_flags": ["--branch", "--strict", "--format"],
        "formats": ["human", "compact", "json"],
        "json_kind": "branch-protection",
        "notes": "Same output contract as `devsecops doctor branch`.",
    },
    {
        "command": "devsecops github doctor",
        "status": "stable",
        "scope": "github",
        "stable_flags": ["--strict", "--format"],
        "formats": ["human", "compact", "json"],
        "json_kind": "github",
        "notes": "Same output contract as `devsecops doctor github`.",
    },
    {
        "command": "devsecops terraform plan",
        "status": "stable",
        "scope": "terraform",
        "stable_flags": ["<environment>", "--no-init", "--create-workspace"],
        "formats": ["human", "terraform-output"],
        "notes": "Delegates to Terraform without hiding Terraform's plan output.",
    },
    {
        "command": "devsecops terraform bootstrap",
        "status": "stable",
        "scope": "terraform",
        "stable_flags": ["--apply"],
        "formats": ["human", "terraform-output"],
        "notes": "Plans by default; mutates AWS only with `--apply`.",
    },
    {
        "command": "devsecops snapshot list",
        "status": "stable",
        "scope": "snapshots",
        "stable_flags": ["--format"],
        "formats": ["human", "json"],
        "json_kind": "snapshots",
        "notes": "Lists local CLI-owned file snapshots.",
    },
    {
        "command": "devsecops snapshot show",
        "status": "stable",
        "scope": "snapshots",
        "stable_flags": ["<selection>", "--format"],
        "formats": ["human", "json"],
        "json_kind": "snapshot",
        "notes": "Shows snapshot manifest and changes since capture.",
    },
    {
        "command": "devsecops snapshot restore",
        "status": "stable",
        "scope": "snapshots",
        "stable_flags": ["--to", "--last", "--dry-run", "--yes"],
        "formats": ["human"],
        "notes": "Restores only local CLI-owned files and creates a safety snapshot before applying.",
    },
    {
        "command": "devsecops preset list",
        "status": "stable",
        "scope": "configuration",
        "stable_flags": [],
        "formats": ["human"],
        "notes": "Lists policy presets.",
    },
    {
        "command": "devsecops preset show",
        "status": "stable",
        "scope": "configuration",
        "stable_flags": ["<name>"],
        "formats": ["human"],
        "notes": "Shows a preset summary.",
    },
    {
        "command": "devsecops preset apply",
        "status": "stable",
        "scope": "configuration",
        "stable_flags": ["<name>", "--render"],
        "formats": ["human"],
        "notes": "Applies a preset while preserving project, region, image, admin role, and backend identity values.",
    },
    {
        "command": "devsecops completion",
        "status": "stable",
        "scope": "completions",
        "stable_flags": ["<shell>", "--program"],
        "formats": ["bash", "zsh", "fish"],
        "notes": "Dependency-free completion scripts for common shells.",
    },
    {
        "command": "devsecops inventory",
        "status": "stable",
        "scope": "stability",
        "stable_flags": ["--format", "--status"],
        "formats": ["human", "markdown", "json"],
        "json_kind": "command-inventory",
        "notes": "Machine-readable stability, deprecation, JSON, config, and generated-artifact contract.",
    },
    {
        "command": "devsecops explain",
        "status": "support",
        "scope": "inspection",
        "stable_flags": ["<topic>"],
        "formats": ["human"],
        "notes": "Human explanation text may be refined across minor releases.",
    },
    {
        "command": "devsecops controls",
        "status": "support",
        "scope": "inspection",
        "stable_flags": ["--format"],
        "formats": ["human", "json"],
        "json_kind": "control-catalog",
        "notes": "Control IDs are stable; prose can be improved.",
    },
    {
        "command": "devsecops envs",
        "status": "support",
        "scope": "inspection",
        "stable_flags": [],
        "formats": ["human"],
        "notes": "Human inspection table.",
    },
    {
        "command": "devsecops architecture",
        "status": "support",
        "scope": "inspection",
        "stable_flags": [],
        "formats": ["human"],
        "notes": "Human architecture tree.",
    },
    {
        "command": "devsecops compose",
        "status": "experimental",
        "scope": "configuration",
        "stable_flags": [],
        "formats": ["human"],
        "notes": "Advanced interactive control editor. Prefer setup for onboarding.",
    },
    {
        "command": "devsecops tui",
        "status": "experimental",
        "scope": "ui",
        "stable_flags": [],
        "formats": ["human"],
        "notes": "Optional Rich/Textual UI bridge; dependency and layout may change.",
    },
    {
        "command": "devsecops start",
        "status": "alias",
        "scope": "first-success",
        "stable_flags": ["--preset", "--render", "--yes"],
        "alias_for": "devsecops setup",
        "formats": ["human"],
        "notes": "Compatibility alias retained through at least v1.0.",
    },
    {
        "command": "devsecops next",
        "status": "alias",
        "scope": "diagnostics",
        "stable_flags": ["--format"],
        "alias_for": "devsecops status",
        "formats": ["human", "json"],
        "json_kind": "next-action",
        "notes": "Compatibility alias that returns only the shared next-action decision.",
    },
    {
        "command": "devsecops readiness",
        "status": "alias",
        "scope": "diagnostics",
        "stable_flags": ["--deep", "--strict", "--format"],
        "alias_for": "devsecops status",
        "formats": ["human", "compact", "json"],
        "json_kind": "readiness",
        "notes": "Compatibility alias with its existing JSON contract retained.",
    },
    {
        "command": "devsecops dashboard",
        "status": "alias",
        "scope": "diagnostics",
        "stable_flags": ["--watch", "--interval", "--mode"],
        "alias_for": "devsecops status",
        "formats": ["human"],
        "notes": "Compatibility alias retained through at least v1.0.",
    },
    {
        "command": "devsecops preflight",
        "status": "alias",
        "scope": "first-success",
        "stable_flags": ["--image-uri", "--environment", "--format"],
        "alias_for": "devsecops image validate",
        "formats": ["human", "compact", "json"],
        "json_kind": "preflight",
        "notes": "Compatibility alias with its existing JSON contract retained.",
    },
    {
        "command": "devsecops render",
        "status": "alias",
        "scope": "rendering",
        "stable_flags": ["--dry-run"],
        "alias_for": "devsecops generate",
        "formats": ["human"],
        "notes": "Compatibility alias retained through at least v1.0.",
    },
    {
        "command": "devsecops init",
        "status": "alias",
        "scope": "configuration",
        "stable_flags": ["--force", "--defaults"],
        "alias_for": "devsecops config new",
        "formats": ["human"],
        "notes": "Compatibility alias retained through at least v1.0.",
    },
    {
        "command": "devsecops validate-config",
        "status": "alias",
        "scope": "configuration",
        "stable_flags": ["--strict", "--format"],
        "alias_for": "devsecops config validate",
        "formats": ["human", "compact", "json"],
        "json_kind": "config",
        "notes": "Compatibility alias retained through at least v1.0.",
    },
    {
        "command": "devsecops set",
        "status": "alias",
        "scope": "configuration",
        "stable_flags": ["<key>", "<value>", "--render"],
        "alias_for": "devsecops config set",
        "formats": ["human"],
        "notes": "Compatibility alias retained through at least v1.0.",
    },
    {
        "command": "devsecops github-setup",
        "status": "alias",
        "scope": "github",
        "stable_flags": ["--write", "--apply", "--deploy-role-arn", "--plan-role-arn", "--snyk-token"],
        "alias_for": "devsecops github setup",
        "formats": ["shell", "human"],
        "notes": "Compatibility alias retained through at least v1.0.",
    },
    {
        "command": "devsecops gh-setup",
        "status": "alias",
        "scope": "github",
        "stable_flags": ["--write", "--apply", "--deploy-role-arn", "--plan-role-arn", "--snyk-token"],
        "alias_for": "devsecops github setup",
        "formats": ["shell", "human"],
        "notes": "Compatibility alias retained through at least v1.0.",
    },
    {
        "command": "devsecops gh-doctor",
        "status": "alias",
        "scope": "github",
        "stable_flags": ["--strict", "--format"],
        "alias_for": "devsecops doctor github",
        "formats": ["human", "compact", "json"],
        "json_kind": "github",
        "notes": "Compatibility alias retained through at least v1.0.",
    },
    {
        "command": "devsecops aws-doctor",
        "status": "alias",
        "scope": "aws",
        "stable_flags": ["--environment", "--strict", "--format"],
        "alias_for": "devsecops doctor aws",
        "formats": ["human", "compact", "json"],
        "json_kind": "aws",
        "notes": "Compatibility alias retained through at least v1.0.",
    },
    {
        "command": "devsecops actions-status",
        "status": "alias",
        "scope": "github",
        "stable_flags": ["--limit", "--strict", "--format"],
        "alias_for": "devsecops doctor actions",
        "formats": ["human", "compact", "json"],
        "json_kind": "github-actions-status",
        "notes": "Compatibility alias retained through at least v1.0.",
    },
    {
        "command": "devsecops gh-status",
        "status": "alias",
        "scope": "github",
        "stable_flags": ["--limit", "--strict", "--format"],
        "alias_for": "devsecops doctor actions",
        "formats": ["human", "compact", "json"],
        "json_kind": "github-actions-status",
        "notes": "Compatibility alias retained through at least v1.0.",
    },
    {
        "command": "devsecops branch-doctor",
        "status": "alias",
        "scope": "github",
        "stable_flags": ["--branch", "--strict", "--format"],
        "alias_for": "devsecops doctor branch",
        "formats": ["human", "compact", "json"],
        "json_kind": "branch-protection",
        "notes": "Compatibility alias retained through at least v1.0.",
    },
    {
        "command": "devsecops plan",
        "status": "alias",
        "scope": "terraform",
        "stable_flags": ["<environment>", "--no-init", "--create-workspace"],
        "alias_for": "devsecops terraform plan",
        "formats": ["human", "terraform-output"],
        "notes": "Compatibility alias retained through at least v1.0.",
    },
    {
        "command": "devsecops bootstrap",
        "status": "alias",
        "scope": "terraform",
        "stable_flags": ["--apply"],
        "alias_for": "devsecops terraform bootstrap",
        "formats": ["human", "terraform-output"],
        "notes": "Compatibility alias retained through at least v1.0.",
    },
    {
        "command": "devsecops snapshots",
        "status": "alias",
        "scope": "snapshots",
        "stable_flags": ["--show"],
        "alias_for": "devsecops snapshot list/show",
        "formats": ["human"],
        "notes": "Compatibility alias retained through at least v1.0.",
    },
    {
        "command": "devsecops rollback",
        "status": "alias",
        "scope": "snapshots",
        "stable_flags": ["--to", "--last", "--dry-run", "--yes"],
        "alias_for": "devsecops snapshot restore",
        "formats": ["human"],
        "notes": "Compatibility alias retained through at least v1.0.",
    },
]
DEPRECATION_POLICY = {
    "aliases": "Aliases remain callable through at least v1.0. New scripts should use the documented grouped command.",
    "experimental_commands": "Experimental commands are excluded from first-success docs and may change or move in any 0.x minor release.",
    "output_formats": "JSON outputs are additive within a schema_version; fields may be added, but existing kind names and documented keys are not renamed without deprecation.",
    "config_fields": "Config fields require schema-versioned migration notes, tests, and upgrade-guide coverage before shipping.",
}
JSON_OUTPUT_CONTRACTS = [
    {
        "kind": "status",
        "commands": ["devsecops status --format json"],
        "stable_keys": ["kind", "schema_version", "score", "breakdown", "gaps", "checks", "context", "next_action"],
    },
    {
        "kind": "image-validation",
        "commands": ["devsecops image validate --format json"],
        "stable_keys": ["kind", "schema_version", "score", "breakdown", "gaps", "checks", "context"],
    },
    {
        "kind": "config",
        "commands": ["devsecops config validate", "devsecops validate-config"],
        "stable_keys": ["kind", "schema_version", "score", "overall_breakdown_score", "breakdown", "gaps", "checks"],
    },
    {
        "kind": "readiness",
        "commands": ["devsecops readiness"],
        "stable_keys": ["kind", "schema_version", "score", "overall_breakdown_score", "breakdown", "gaps", "checks", "context"],
    },
    {
        "kind": "preflight",
        "commands": ["devsecops preflight"],
        "stable_keys": ["kind", "schema_version", "score", "overall_breakdown_score", "breakdown", "gaps", "checks", "context"],
    },
    {
        "kind": "health",
        "commands": ["devsecops health"],
        "stable_keys": ["kind", "schema_version", "score", "overall_breakdown_score", "breakdown", "gaps", "checks", "context"],
    },
    {
        "kind": "github-actions-status",
        "commands": ["devsecops github status", "devsecops doctor actions"],
        "stable_keys": ["kind", "schema_version", "error", "runs", "failed_jobs", "failed_steps", "next_actions"],
    },
    {
        "kind": "aws-outputs",
        "commands": ["devsecops aws outputs"],
        "stable_keys": ["kind", "schema_version", "environment", "outputs", "checks", "next_actions"],
    },
    {
        "kind": "snapshots",
        "commands": ["devsecops snapshot list"],
        "stable_keys": ["kind", "schema_version", "snapshots"],
    },
    {
        "kind": "snapshot",
        "commands": ["devsecops snapshot show"],
        "stable_keys": ["kind", "schema_version", "snapshot"],
    },
    {
        "kind": "audit-evidence",
        "commands": ["devsecops report --format json"],
        "stable_keys": ["kind", "schema_version", "cli_version", "project", "readiness", "config_validation", "controls"],
    },
    {
        "kind": "control-catalog",
        "commands": ["devsecops controls --format json"],
        "stable_keys": ["kind", "schema_version", "controls"],
    },
    {
        "kind": "command-inventory",
        "commands": ["devsecops inventory --format json"],
        "stable_keys": ["kind", "schema_version", "commands", "deprecation_policy", "json_outputs", "generated_artifacts"],
    },
    {
        "kind": "next-action",
        "commands": ["devsecops next --format json"],
        "stable_keys": ["kind", "schema_version", "context", "action", "command", "detail", "why", "changes", "blocked", "docs"],
    },
    {
        "kind": "release-candidate-evidence",
        "commands": ["devsecops evidence collect --rc"],
        "stable_keys": ["kind", "schema_version", "generated_at", "output_dir", "files", "terraform_validate"],
    },
    {
        "kind": "v1-criteria",
        "commands": ["devsecops criteria --format json"],
        "stable_keys": ["kind", "schema_version", "cli_version", "stable_ready", "criteria", "stable_release_gates", "next_actions"],
    },
]
GENERATED_ARTIFACT_CONTRACTS = [
    {
        "path": str(GENERATED_TFVARS),
        "producer": "devsecops generate",
        "compatibility": "stable",
        "rerender_required_when": ["config values change", "config schema migration changes normalized values", "Terraform variable contract changes"],
        "expected_diffs": ["HCL assignment value changes", "environment_config map changes", "CLI-owned header updates only on generator policy changes"],
    },
    {
        "path": str(DIST_DIR / "backend.tf"),
        "producer": "devsecops generate",
        "compatibility": "stable-template",
        "rerender_required_when": ["backend.* config values change", "Terraform backend template policy changes"],
        "expected_diffs": ["S3 backend attribute value changes"],
    },
    {
        "path": str(DIST_DIR / "github-variables.env"),
        "producer": "devsecops generate",
        "compatibility": "stable",
        "rerender_required_when": ["GitHub variable source config changes"],
        "expected_diffs": ["PROJECT_NAME, LAMBDA_IMAGE_URI, ENABLE_* or PROD_APPROVAL_ENVIRONMENT value changes"],
    },
    {
        "path": str(DIST_DIR / "github-setup.sh"),
        "producer": "devsecops generate or devsecops github setup --write",
        "compatibility": "stable-helper",
        "rerender_required_when": ["GitHub variable source config changes", "required secret contract changes"],
        "expected_diffs": ["gh variable commands", "optional versus required SNYK_TOKEN command", "CLI-owned header updates"],
    },
    {
        "path": str(DIST_DIR / "setup-checklist.md"),
        "producer": "devsecops generate",
        "compatibility": "stable-helper",
        "rerender_required_when": ["GitHub, backend, or branch-protection checklist contract changes"],
        "expected_diffs": ["checklist item values or required item additions"],
    },
    {
        "path": str(DIST_DIR / "readiness-report.md"),
        "producer": "devsecops report",
        "compatibility": "stable-report",
        "rerender_required_when": ["readiness checks change", "config values change", "environment state changes"],
        "expected_diffs": ["Generated timestamp", "score/check/action rows", "control or environment rows"],
    },
    {
        "path": str(AUDIT_REPORT),
        "producer": "devsecops report --format json",
        "compatibility": "stable-json",
        "rerender_required_when": ["audit evidence, readiness, config, or control state changes"],
        "expected_diffs": ["generated_at timestamp", "readiness/config/control payload changes"],
    },
    {
        "path": str(RC_EVIDENCE_DIR / "manifest.json"),
        "producer": "devsecops evidence collect --rc",
        "compatibility": "stable-json",
        "rerender_required_when": ["release-candidate evidence is collected"],
        "expected_diffs": ["generated_at timestamp", "evidence file list", "Terraform validation status"],
    },
    {
        "path": str(RC_EVIDENCE_DIR / "criteria.json"),
        "producer": "devsecops evidence collect --rc",
        "compatibility": "stable-json",
        "rerender_required_when": ["release-candidate evidence is collected", "Version 1.0 criteria or stable-release gates change"],
        "expected_diffs": ["generated_at timestamp", "criteria status", "stable-release gate status", "next actions"],
    },
]

def command_contracts(status: str = "all") -> list[dict[str, Any]]:
    if status == "all":
        return [dict(item) for item in COMMAND_CONTRACTS]
    return [dict(item) for item in COMMAND_CONTRACTS if item["status"] == status]


def command_contract_rows(status: str = "all") -> list[list[str]]:
    return [
        [
            str(item["command"]),
            str(item["status"]),
            str(item["scope"]),
            ", ".join(str(flag) for flag in item.get("stable_flags", [])) or "-",
            str(item.get("alias_for") or item.get("json_kind") or ""),
        ]
        for item in command_contracts(status)
    ]


def command_inventory_markdown(status: str = "all") -> str:
    return "\n\n".join(
        [
            "# DevSecOps Command Inventory",
            f"Contract schema version: `{CONTRACT_SCHEMA_VERSION}`",
            f"Status filter: `{status}`",
            markdown_table(["Command", "Status", "Scope", "Stable Flags", "Alias/JSON"], command_contract_rows(status)),
            "## Deprecation Policy",
            markdown_table(["Surface", "Policy"], [[key, value] for key, value in DEPRECATION_POLICY.items()]),
            "## JSON Output Contract",
            markdown_table(
                ["Kind", "Commands", "Stable Keys"],
                [
                    [
                        item["kind"],
                        ", ".join(item["commands"]),
                        ", ".join(item["stable_keys"]),
                    ]
                    for item in JSON_OUTPUT_CONTRACTS
                ],
            ),
            "## Generated Artifact Contract",
            markdown_table(
                ["Path", "Producer", "Compatibility", "Re-render When"],
                [
                    [
                        item["path"],
                        item["producer"],
                        item["compatibility"],
                        "; ".join(item["rerender_required_when"]),
                    ]
                    for item in GENERATED_ARTIFACT_CONTRACTS
                ],
            ),
            "",
        ]
    )


def inventory_payload(status: str = "all") -> dict[str, Any]:
    return {
        "kind": "command-inventory",
        "schema_version": CONTRACT_SCHEMA_VERSION,
        "cli_version": VERSION,
        "status_filter": status,
        "commands": command_contracts(status),
        "deprecation_policy": DEPRECATION_POLICY,
        "json_outputs": JSON_OUTPUT_CONTRACTS,
        "generated_artifacts": GENERATED_ARTIFACT_CONTRACTS,
        "config_migration": CONFIG_MIGRATION_CONTRACT,
        "exit_codes": {
            "0": "ok",
            "1": "validation failed or invalid local selection",
            "2": "required external tool is missing",
            "3": "external authentication is missing or invalid",
            "70": "unexpected runtime error",
            "130": "interrupted",
        },
    }



__all__ = [
    "COMMAND_CONTRACTS",
    "CONTRACT_SCHEMA_VERSION",
    "DEPRECATION_POLICY",
    "GENERATED_ARTIFACT_CONTRACTS",
    "JSON_OUTPUT_CONTRACTS",
    "command_contract_rows",
    "command_contracts",
    "command_inventory_markdown",
    "inventory_payload",
]
